api/urls.py
from django.urls import path

from ussdapp.views import check_it

app_name='api'
urlpatterns = [
    path('', check_it, name='check_it'),
]

chekkit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('products/', include('product.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('invitations/', include('invitations.urls', namespace='invitations')),
]

frontend/urls.py
from django.urls import path

from . import views

app_name= 'frontend'
urlpatterns = [
    path('', views.overview, name='overview'),
    path('activity/', views.activity, name='activity'),
    path('analytics/', views.analytics, name='analytics'),
    path('collections/', views.collections, name='collections'),
]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.create_product_line, name='create_product_line'),
    path('<uuid:uuid>/', views.product_line, name='detail_productline'),
    path('batch/<uuid:uuid>/', views.batch_detail, name='batch_detail'),
    path('generate/batch/<uuid:uuid>/', views.generate_product_codes_for_batch,
         name='generate_product_codes_for_batch'),
    path('generate/<uuid:uuid>/', views.generate_product_codes, name='generate_product_codes_for_line'),
    path('generate/', views.generate_product_codes, name='generate_product_codes'),
    path('codes/<uuid:uuid><int:id>', views.product_code, name='code'),


]

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from accounts.forms import ManufacturerForm, ProfileForm
from accounts.models import Location
from product.models import ProductLine, CodeCollection


# Create your views here.
def overview(request):
    if request.user.is_authenticated:
        if not request.user.profile.activated:
            if request.method == 'POST':
                create_manufacturer_form = ManufacturerForm(request.POST)
                profile_form = ProfileForm(request.POST)
                if create_manufacturer_form.is_valid() and profile_form.is_valid():
                    manufacturer = create_manufacturer_form.save()
                    position = profile_form.cleaned_data['position']
                    profile = request.user.profile
                    profile.manufacturer = manufacturer
                    profile.activated = True
                    profile.position = position
                    Location.objects.create(name=manufacturer.address, manufacturer=manufacturer)
                    profile.save()
                return redirect(reverse('frontend:overview'))
            else:
                create_manufacturer_form = ManufacturerForm()
                profile_form = ProfileForm(initial={})
            return render(request, 'frontend/overview.html',
                          {'create_manufacturer_form': create_manufacturer_form, 'profile_form': profile_form})
        else:
            product_lines = ProductLine.objects.filter(manufacturer__profile__user=request.user)
            context = {
                'product_lines': product_lines,
                'overview': True
            }
            return render(request, 'frontend/overview.html', context)
    else:
        return render(request, 'frontend/landing.html', {})


def activity(request):
    context = {
        'activity': True
    }
    return render(request, 'frontend/activity.html', context)


def analytics(request):
    context = {
        'analytics': True
    }
    return render(request, 'frontend/analytics.html', context)


def collections(request):
    collection_object = CodeCollection.objects.filter(manufacturer=request.user.profile.manufacturer)
    context = {
        'collection_object': collection_object,
        'collections': True
    }
    return render(request, 'frontend/collections.html', context)

frontend/templates/partials/sidebar.html
{% load product_lines_tag %}

<aside class="menu w3-container w3-padding-large">
    <p class="menu-label w3-large w3-margin-top w3-text-light-green" style="font-weight: 900">
        General
    </p>
    <ul class="menu-list">
        <li class="w3-xlarge"><a
                class="{% if overview %}w3-light-green w3-text-white trans-400 has-text-weight-bold{% endif %}"
                href="/"><i class="fas fa-info-circle"></i>&nbsp;&nbsp;Oveview</a></li>
        <li class="w3-xlarge"><a
                class="{% if activity %}w3-light-green w3-text-white trans-400 has-text-weight-bold{% endif %}"
                href="{% url 'frontend:activity' %}"><i class="fas fa-chart-line"></i>&nbsp;&nbsp;Activity</a></li>
        <li class="w3-xlarge"><a
                class="{% if analytics %}w3-light-green w3-text-white trans-400 has-text-weight-bold{% endif %}"
                href="{% url 'frontend:analytics' %}"><i class="fas fa-chart-pie"></i>&nbsp;&nbsp;Analytics</a></li>
        <li class="w3-xlarge"><a
                class="{% if collections %}w3-light-green w3-text-white trans-400 has-text-weight-bold{% endif %}"
                href="{% url 'frontend:collections' %}"><i class="fas fa-layer-group"></i>&nbsp;&nbsp;Collections</a>
        </li>
    </ul>
    <p class="menu-label w3-large w3-margin-top w3-text-light-green" style="font-weight: 900">
        Product Lines
    </p>
    <ul class="menu-list">
        {% with request|product_lines as pl %}
            {% for product_line in pl %}

                <li class="w3-xlarge" title="{{ product_line.product_name }}" id="{{ product_line.uuid }}">
                    <a class="{% if product_line.uuid == product_line_object.uuid %}w3-light-green w3-text-white trans-400{% endif %}"
                       href="{% url 'product:detail_productline' product_line.uuid %}"><i class="fas fa-link"></i>&nbsp;&nbsp;{{ product_line.product_name }}
                    </a>
                </li>
            {% endfor %}

        {% endwith %}

    </ul>
    {% with request|batch_numbers as bn %}
        {% if bn %}
            <p class="menu-label w3-large w3-margin-top w3-text-light-green" style="font-weight: 900">
                Batch
            </p>
            <ul class="menu-list">
                {% for batch_number in bn %}

                    <li class="w3-xlarge" id="{{ batch_number.uuid }}">
                        <a class="{% if batch_number.uuid == batch_object.uuid %}w3-light-green w3-text-white trans-400{% endif %}"
                           href="{% url 'product:batch_detail' batch_number.uuid %}"><i class="fas fa-hashtag"></i>&nbsp;&nbsp;{{ batch_number.batch_number }}
                            | {{ batch_number.product_line.product_name }}</a>
                    </li>
                {% endfor %}

            </ul>
        {% endif %}
    {% endwith %}
</aside>