api/urls.py
from django.urls import path

from ussdapp.views import check_it

app_name='api'
urlpatterns = [
    path('', check_it, name='check_it'),
]

chekkit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('products/', include('product.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('invitations/', include('invitations.urls', namespace='invitations')),
]

frontend/urls.py
from django.urls import path

from . import views

app_name= 'frontend'
urlpatterns = [
    path('', views.overview, name='overview'),
    path('activity/', views.activity, name='activity'),
    path('analytics/', views.analytics, name='analytics'),
    path('collections/', views.collections, name='collections'),
]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.create_product_line, name='create_product_line'),
    path('<uuid:uuid>/', views.product_line, name='detail_productline'),
    path('batch/<uuid:uuid>/', views.batch_detail, name='batch_detail'),
    path('generate/batch/<uuid:uuid>/', views.generate_product_codes_for_batch,
         name='generate_product_codes_for_batch'),
    path('generate/<uuid:uuid>/', views.generate_product_codes, name='generate_product_codes_for_line'),
    path('generate/', views.generate_product_codes, name='generate_product_codes'),
    path('codes/<uuid:uuid><int:id>', views.product_code, name='code'),


]

product/models.py
import random
import uuid
from datetime import datetime
from random import randint

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.timesince import timesince
from django.utils.translation import gettext_lazy as _

from accounts.models import Manufacturer, Location


def validate_code_length(value):
    if len(str(value)) != 3:
        raise ValidationError(
            _('Product Code must have a length of 3 should not start with zeros')
        )


class ProductLine(models.Model):
    uuid = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False)
    product_name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    photo = models.ImageField(upload_to='images', blank=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, blank=True, null=True)
    is_active = models.BooleanField(default=False)
    code = models.IntegerField(validators=[validate_code_length])

    class Meta:
        verbose_name = 'Product Line'
        verbose_name_plural = 'Product Lines'

    def __str__(self):
        return "{} ({})".format(self.product_name, self.manufacturer)

    def save(self, *args, **kwargs):
        if self._state.adding:
            filtered_taken_codes = list(range(100, 999))
            for product_line in ProductLine.objects.filter(manufacturer=self.manufacturer):
                filtered_taken_codes.remove(product_line.code)
            self.code = random.choice(filtered_taken_codes)
        super().save(*args, **kwargs)


class Batch(models.Model):
    product_line = models.ForeignKey(ProductLine, on_delete=models.CASCADE)
    uuid = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False)
    production_date = models.DateField(default=datetime.now)
    expiry_date = models.DateField(default=datetime.now)
    batch_number = models.IntegerField(blank=True, null=True, default=randint(0, 999999))
    location = models.ForeignKey(Location, on_delete=models.CASCADE)

    @property
    def manufacturer(self):
        try:
            return self.location.manufacturer_name
        except:
            pass

    def __str__(self):
        return "{} ({})".format(self.batch_number, self.manufacturer)

    class Meta:
        verbose_name = 'Batch Number'
        verbose_name_plural = 'Batch Numbers'


class CodeCollection(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(blank=True, null=True)
    product_line = models.ForeignKey(ProductLine, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return "{} Codes Generated By: {} ({})".format(self.quantity, self.manufacturer, timesince(self.created))


class ProductCode(models.Model):
    product_code = models.BigIntegerField(unique=True)
    product_line = models.ForeignKey(ProductLine, on_delete=models.CASCADE)
    collection = models.ForeignKey(CodeCollection, on_delete=models.CASCADE, null=True, blank=True)
    batch_number = models.ForeignKey(Batch, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    activated = models.BooleanField(default=False)
    activation_count = models.IntegerField(default=0)

    @property
    def readable_product_code(self):
        code = str(self.product_code)
        return code[0:4] + ' ' + code[4:8] + ' ' + code[8:12] + ' ' + code[12:16]

    def __str__(self):
        return str(self.product_code)

    def rand_string(self, config=None):
        if config is None:
            config = {"length": 5}
        i = 0
        result_string = ""
        while (i < config["length"]):
            result_string += (str)(random.randint(0, 9))

            i += 1
        return (result_string)

    def get_timestamp(self):
        return str(datetime.timestamp(datetime.now()))

    def generate_code(self, company_code, product_line):
        common_code = str(company_code) + str(product_line)
        time_stamp = self.get_timestamp()

        new_code = common_code + self.rand_string({"length": 6}) + time_stamp[14:]
        if new_code.__len__() < 16:
            new_code += ("0" * (16 - len(new_code)))

        return new_code

    def save(self, *args, **kwargs):
        if self._state.adding:
            self.product_code = self.generate_code(self.product_line.manufacturer.code, self.product_line.code)
        super().save(*args, **kwargs)

product/forms.py
from django import forms
from django.forms import ModelForm

from accounts.models import Location
from .models import ProductLine, ProductCode, Batch, CodeCollection


class ProductLineForm(ModelForm):

    class Meta:
        model = ProductLine
        fields = ['product_name', 'description', 'photo']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3}),
        }


class CodeCollectionForm(ModelForm):
    class Meta:
        model = CodeCollection
        fields = ('quantity',)


class ProductCodeForm(ModelForm):
    def __init__(self, manufacturer=None, *args, **kwargs):
        super(ProductCodeForm, self).__init__(*args, **kwargs)
        if manufacturer:
            self.fields['product_line'].queryset = ProductLine.objects.filter(manufacturer=manufacturer)

    class Meta:
        model = ProductCode
        fields = ['product_line']


class ProductCodeFromBatchForm(ModelForm):
    def __init__(self, manufacturer=None, *args, **kwargs):
        super(ProductCodeFromBatchForm, self).__init__(*args, **kwargs)
        if manufacturer:
            self.fields['product_line'].queryset = ProductLine.objects.filter(manufacturer=manufacturer)

    class Meta:
        model = ProductCode
        fields = ['batch_number']


class BatchForm(ModelForm):
    def __init__(self, manufacturer, *args, **kwargs):
        super(BatchForm, self).__init__(*args, **kwargs)
        self.fields['location'].queryset = Location.objects.filter(manufacturer=manufacturer)

    class Meta:
        model = Batch
        exclude = ('product_line',)

product/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse

from product.models import ProductLine, ProductCode, Batch
from .forms import ProductLineForm, ProductCodeForm, BatchForm, ProductCodeFromBatchForm, CodeCollectionForm


# Create your views here.
@login_required()
def create_product_line(request):
    next = request.GET.get('next', '/')
    if request.method == 'POST':
        create_product_line_form = ProductLineForm(request.POST, request.FILES)
        if create_product_line_form.is_valid():
            product_line = create_product_line_form.save(commit=False)
            product_line.manufacturer = request.user.profile.manufacturer
            product_line.save()
            next = request.POST.get('next')
            if next != '/':
                return redirect(next + str(product_line.uuid) + '/')
            else:
                return redirect(reverse('product:detail_productline', args=(product_line.uuid,)))
    else:
        create_product_line_form = ProductLineForm()
    return render(request, 'product/create_product_line.html',
                  {'create_product_line_form': create_product_line_form, 'next': next})




def product_line(request, uuid):
    product_line_object = ProductLine.objects.get(uuid=uuid)
    product_codes = ProductCode.objects.filter(product_line=product_line_object).order_by('created')
    paginator = Paginator(product_codes, 20)

    page = request.GET.get('page')
    product_codes = paginator.get_page(page)
    return render(request, 'product/product_line_detail.html',
                  {'product_line_object': product_line_object, 'product_codes': product_codes})


def batch_detail(request, uuid):
    batch = Batch.objects.get(uuid=uuid)
    product_codes = ProductCode.objects.filter(batch_number__uuid=uuid)
    paginator = Paginator(product_codes, 20)

    page = request.GET.get('page')
    product_codes = paginator.get_page(page)
    return render(request, 'batch/batch_detail.html', {'product_codes': product_codes, 'batch_object': batch})


@login_required()
def generate_product_codes(request, uuid=None):
    current_user_manufacturer = request.user.profile.manufacturer
    if request.method == 'POST':
        collection_form = CodeCollectionForm(request.POST)
        product_form = ProductCodeForm(current_user_manufacturer, request.POST)
        batch_form = BatchForm(current_user_manufacturer, request.POST)
        print('product: ', product_form.is_valid())
        print('batch: ', batch_form.is_valid())
        if product_form.is_valid() and collection_form.is_valid() and batch_form.is_valid():
            collection = collection_form.save(commit=False)
            product = product_form.save(commit=False)
            batch = batch_form.save(commit=False)

            collection.manufacturer = product.product_line.manufacturer
            collection.product_line = product.product_line
            collection.save()

            batch.product_line = product.product_line
            batch.save()

            for c_time in range(0, collection.quantity):
                ProductCode.objects.create(batch_number=batch, product_line=product.product_line, collection=collection)

            return redirect(reverse('product:detail_productline', args=(product.product_line.uuid,)))
        return redirect('/')
    else:
        batch_form = BatchForm(current_user_manufacturer)
        collection_form = CodeCollectionForm()
        if uuid:
            product_line = ProductLine.objects.get(uuid=uuid)
            product_form = ProductCodeForm(current_user_manufacturer, initial={'product_line': product_line})
        else:
            product_form = ProductCodeForm(current_user_manufacturer)
        return render(request, 'product/generate_product_codes.html',
                      {'product_form': product_form, 'batch_form': batch_form,
                       'manufacturer': current_user_manufacturer, 'collection_form': collection_form})


@login_required()
def generate_product_codes_for_batch(request, uuid):
    batch = Batch.objects.get(uuid=uuid)
    if request.method == 'POST':
        product_form = ProductCodeFromBatchForm(request.POST)
        if product_form.is_valid():

            product = product_form.save(commit=False)

            quantity = product_form.cleaned_data['quantity']

            for c_time in range(0, quantity):
                ProductCode.objects.create(batch_number=batch, generated_by=request.user,
                                           product_line=batch.product_line)

            return redirect(reverse('product:batch_detail', args=(batch.uuid,)))
    else:
        product_form = ProductCodeFromBatchForm(initial={'batch_number': batch})
        return render(request, 'product/generate_product_codes.html',
                      {'product_form': product_form,
                       'manufacturer': request.user.profile.manufacturer})


def product_code(request, uuid, id):
    product_code_object = ProductCode.objects.get(id=id, product_line__uuid=uuid)
    return render(request, 'product/product_code.html', {'product_code_object': product_code_object})

product/templates/product/create_product_line.html
{% extends 'index.html' %}
{% block title %}
    Create Product Line
{% endblock %}
{% load bulma_tags %}
{% block main %}
    <div class="modal is-active" id="cpl-modal">
        <div class="modal-background" id="cpl-modal-background"></div>
        <div class="modal-card">
            <header class="modal-card-head">
                <p class="modal-card-title">Create Product Line</p>
            </header>
            <form action="{% url 'product:create_product_line' %}" method="post" enctype="multipart/form-data">
                <section class="modal-card-body">
                    <input type="hidden" name="next" value="{{ next }}"/>
                    {% csrf_token %}
                    {{ create_product_line_form|bulma }}
                </section>
                <footer class="modal-card-foot">
                    <input type="submit" class="button w3-light-green w3-text-white is-text"
                           value="Create Product Line"/>

                </footer>
            </form>
        </div>
    </div>


{% endblock %}
{% block script %}
    <script>
        let modalBackground = document.getElementById('cpl-modal-background');
        let modal = document.getElementById('cpl-modal');
        modalBackground.addEventListener('click', () => {
            window.location.href = '/'
        })
    </script>
{% endblock %}

product/templates/product/generate_product_codes.html
{% extends 'index.html' %}
{% block title %}
    Generate Product Codes
{% endblock %}
{% load bulma_tags staticfiles static %}

{% block main %}
    <div class="modal is-active" id="gpc-modal">
        <div class="modal-background" id="gpc-modal-background"></div>
        <div class="modal-card">
            <header class="modal-card-head">
                <p class="modal-card-title">Generate Codes, {{ manufacturer }}</p>
            </header>
            <form action="." method="post">
                <section class="modal-card-body">
                    {% csrf_token %}
                    {% if batch_form %}
                        {{ batch_form|bulma }}
                    {% endif %}
                    {{ collection_form|bulma }}
                    {{ product_form|bulma }}
                </section>
                <footer class="modal-card-foot">
                    <input type="submit" class="button w3-light-green w3-text-white is-text"
                           value="Generate Codes"/>
                </footer>
            </form>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        let modalBackground = document.getElementById('gpc-modal-background');
        let modal = document.getElementById('gpc-modal');
        modalBackground.addEventListener('click', () => {
            window.location.href = '/'
        })
    </script>
{% endblock %}

product/templates/product/product_code.html
{% extends 'index.html' %}
{% block title %}
    {{ product_code_object }}
{% endblock %}
{% block main %}
    <header class="hero is-small is-black is-small">
        <div class="hero-body w3-center" style="max-width: 400px; max-height: 400px; margin: auto">
            {% with product_code_object as product_code %}
                {% include 'partials/product_code.html' %}
            {% endwith %}
        </div>
    </header>

{% endblock %}

product/templates/product/product_line_detail.html
{% extends 'index.html' %}
{% block title %}
    {{ product_line_object }}
{% endblock %}
{% load thumbnail %}
{% block main %}
    <header class="hero is-small w3-light-green w3-card-2">
        <div class="hero-body columns">
            <div class="column is-2">
                <figure class="image is-128x128">
                    {% if product_line_object.photo %}

                        {% thumbnail product_line_object.photo "128x128" crop="center" as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
                                 title="Image of {{ product_line_object.product_name }}">
                        {% endthumbnail %}
                    {% else %}
                        <img src="https://bulma.io/images/placeholders/480x480.png"
                             alt="Placeholder image for {{ product_line_object.product_name }}">
                    {% endif %}
                </figure>
            </div>
            <div class="column is-10 w3-container w3-margin-left">

                <h1 class="title w3-text-white">{{ product_line_object }}</h1>
                <p class="subtitle w3-text-white">{{ product_line_object.description|default:'Product Description ...' }}</p>
                <a class="w3-btn w3-white"
                   href="{% url 'product:generate_product_codes_for_line' product_line_object.uuid %}">Generate Product
                    Codes</a>
                <a class="w3-btn w3-white"
                   href="{% url 'frontend:collections' %}">View Collections</a>
            </div>
        </div>
    </header>
    <section class="w3-margin">
        <div class="columns is-multiline">
            {% for product_code in product_codes %}
                <a class="column is-3 w3-center"
                   href="{% url 'product:code' product_code.product_line.uuid product_code.id %}">
                    {% include 'partials/product_code.html' %}
                </a>
            {% endfor %}
            <span style="margin: auto">
                {% if product_codes.has_next %}
                    {% with product_codes as page_obj %}
                        {% include 'partials/paginator.html' %}
                    {% endwith %}

                {% endif %}
            </span>
        </div>
    </section>
{% endblock %}

product/templates/product/view_product_codes.html
{% extends 'base.html' %}
{% load bulma_tags staticfiles static %}

{% block content %}
<div class="w3-quarter w3-light-grey">
	{% include 'partials/sidebar.html' %}
</div>
<div class="w3-threequarter">
        <header class="hero is-small is-link">
            <div class="hero-body columns">
                <div class="column is-2">
                    <figure class="image is-128x128">
                        <img src="https://bulma.io/images/placeholders/480x480.png" alt="">
                    </figure>
                </div>
                <div class="column is-10 w3-container">

                    <h1 class="title">{{ productline.product_name }}</h1>
                    <p class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet assumenda debitis
                        deleniti distinctio id illum inventore, perspiciatis quam quas quia ratione recusandae repellat
                        sint soluta temporibus tenetur unde veritatis voluptate.</p>
                    <a class="button is-dark is-medium" href="{% url 'product:generate_product_line_codes' productline.uuid  %}">Generate Product Codes for {{ productline.product_name }}</a>
                </div>
            </div>
        </header>
</div>
<section class="w3-margin">
	<div class="w3-container">
		<h2>Cards</h2>
		<p>Create paper-like cards with the w3-card classes:</p>

  <div class="w3-panel w3-card"><p>w3-card</p></div>
  <div class="w3-panel w3-card-2"><p>w3-card-2</p></div>
  <div class="w3-panel w3-card-4"><p>w3-card-4</p></div>
</div>
</section>

{% endblock %}