accounts/urls.py
from django.urls import path

from accounts import views

app_name='accounts'
urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('manufacturer/', views.manufacturer, name='manufacturer'),
    path('create_manufacturer/', views.create_manufacturer, name='create_manufacturer'),
]

api/urls.py
from django.urls import path

from ussdapp.views import check_it

app_name='api'
urlpatterns = [
    path('', check_it, name='check_it'),
]

chekkit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('products/', include('product.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('invitations/', include('invitations.urls', namespace='invitations')),
]

frontend/urls.py
from django.urls import path

from . import views

app_name= 'frontend'
urlpatterns = [
    path('', views.overview, name='overview'),
    path('activity/', views.activity, name='activity'),
    path('analytics/', views.analytics, name='analytics'),
    path('collections/', views.collections, name='collections'),
]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.create_product_line, name='create_product_line'),
    path('<uuid:uuid>/', views.product_line, name='detail_productline'),
    path('batch/<uuid:uuid>/', views.batch_detail, name='batch_detail'),
    path('generate/batch/<uuid:uuid>/', views.generate_product_codes_for_batch,
         name='generate_product_codes_for_batch'),
    path('generate/<uuid:uuid>/', views.generate_product_codes, name='generate_product_codes_for_line'),
    path('generate/', views.generate_product_codes, name='generate_product_codes'),
    path('codes/<uuid:uuid><int:id>', views.product_code, name='code'),


]

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from accounts.forms import ManufacturerForm, ProfileForm
from accounts.models import Location
from product.models import ProductLine, CodeCollection


# Create your views here.
def overview(request):
    if request.user.is_authenticated:
        if not request.user.profile.activated:
            if request.method == 'POST':
                create_manufacturer_form = ManufacturerForm(request.POST)
                profile_form = ProfileForm(request.POST)
                if create_manufacturer_form.is_valid() and profile_form.is_valid():
                    manufacturer = create_manufacturer_form.save()
                    position = profile_form.cleaned_data['position']
                    profile = request.user.profile
                    profile.manufacturer = manufacturer
                    profile.activated = True
                    profile.position = position
                    Location.objects.create(name=manufacturer.address, manufacturer=manufacturer)
                    profile.save()
                return redirect(reverse('frontend:overview'))
            else:
                create_manufacturer_form = ManufacturerForm()
                profile_form = ProfileForm(initial={})
            return render(request, 'frontend/overview.html',
                          {'create_manufacturer_form': create_manufacturer_form, 'profile_form': profile_form})
        else:
            product_lines = ProductLine.objects.filter(manufacturer__profile__user=request.user)
            context = {
                'product_lines': product_lines,
                'overview': True
            }
            return render(request, 'frontend/overview.html', context)
    else:
        return render(request, 'frontend/landing.html', {})


def activity(request):
    context = {
        'activity': True
    }
    return render(request, 'frontend/activity.html', context)


def analytics(request):
    context = {
        'analytics': True
    }
    return render(request, 'frontend/analytics.html', context)


def collections(request):
    collection_object = CodeCollection.objects.filter(manufacturer=request.user.profile.manufacturer)
    context = {
        'collection_object': collection_object,
        'collections': True
    }
    return render(request, 'frontend/collections.html', context)

frontend/templates/base.html
{% load static staticfiles product_lines_tag %}
<!DOCTYPE html>
<html>
<head>
    <style>
        @font-face {
            font-family: 'CircularStd-Book';
            src: url('{% static 'frontend/fonts/circularstd-book.woff2' %}') format('woff2'),
            url('{% static 'frontend/fonts/circularstd-book.ttf' %}') format('truetype'),
            url('{% static 'frontend/fonts/circularstd-book.woff' %}') format('woff');
            font-weight: normal;
            font-style: normal;
        }
    </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}

    {% endblock %} | Chekkit</title>
    <link rel="stylesheet" href="{% static 'frontend/css/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'frontend/css/w3.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>
    <link rel="stylesheet" href="{% static 'frontend/css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    {% block css %}

    {% endblock %}
    <style>
        .logo {
            font-family: 'Roboto', sans-serif;
        }

    </style>
</head>
<body>
<nav class="navbar w3-border-bottom w3-card-4" role="navigation" aria-label="main navigation"
     style="padding: 6px 0; position: fixed; top: 0; width: 100%;{% if request.user.is_authenticated and not request.user.profile.activated %}z-index:-1{% endif %}">

    <div class="navbar-brand">
        <a href="/" style="margin-left:30px">
            <img src="{% static 'frontend/images/chekkit.png' %}" width="60" height="60">
        </a>

        <a role="button" class="navbar-burger w3-margin-right" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>

    </div>
    <div class="navbar-menu">

        <div class="navbar-end">
            {% if request.user.is_authenticated %}
                {% if request.user.profile.manufacturer %}
                    <a class="navbar-item" href="{% url 'product:create_product_line' %}">Create Product Line</a>
                    {% with request|product_lines as pl %}
                        {% if not pl|length == 0 %}

                            <a class="navbar-item" href="{% url 'product:generate_product_codes' %}">Generate Product
                                Codes</a>
                        {% endif %}
                    {% endwith %}
                    <a class="navbar-item w3-text-light-green has-text-weight-bold" style="text-decoration: underline"
                       href="{% url 'accounts:manufacturer' %}">
                        {{ request.user.profile.manufacturer }}
                    </a>
                {% else %}
                    <a class="navbar-item"
                       href="{% url 'accounts:create_manufacturer' %}">
                        Create Manufacturer Account
                    </a>
                {% endif %}
                <a class="navbar-item w3-opacity" href="{% url 'account_logout' %}">Logout</a>

            {% else %}
                <a class="navbar-item" href="{% url 'account_login' %}">Login</a>
                <a class="navbar-item" href="{% url 'account_signup' %}">Register</a>

            {% endif %}
        </div>
    </div>
</nav>
<div class="navbar-offset">
    {% block content %}

    {% endblock %}
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', () => {

        // Get all "navbar-burger" elements
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

        // Check if there are any navbar burgers
        if ($navbarBurgers.length > 0) {

            // Add a click event on each of them
            $navbarBurgers.forEach(el => {
                el.addEventListener('click', () => {

                    // Get the target from the "data-target" attribute
                    const target = el.dataset.target;
                    const $target = document.getElementById(target);

                    // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                    el.classList.toggle('is-active');
                    $target.classList.toggle('is-active');

                });
            });
        }

    });
    {# TODO: add code for disabling button when it is clicked one#}
</script>
{% block script %}

{% endblock %}

</body>
</html>

frontend/templates/index.html
{% extends 'base.html' %}
{% block title %}

{% endblock %}
{% block content %}
    <div class="w3-quarter w3-white w3-card-4 w3-hide-small"
         style="overflow-y:auto;top: 70px; bottom: 0; height: 100%; position: fixed">
        {% include 'partials/sidebar.html' %}
    </div>
    <div class="w3-threequarter w3-animate-right w3-right">
    {% block main %}

    {% endblock %}
    </div>


{% endblock %}
{% block script %}

{% endblock %}